### ISSUE TITLE
Write a section for "Correcting data based on NDA QC Report"

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/nda-bids-upload#6]
See title.

**Comment by kweldon1** [comment]
Can you clarify Eric? Thanks!

**Comment by ericearl** [comment]
@kweldon1 If we chat over Slack that kind of defeats the purpose of open source Issue discussions. The issue title is suggesting there be a section on how to handle working with NDA QC reports if that matters for users of this tool.

Imagine you just finished using this tool and NDA comes back with corrections for you. A little troubleshooting doc on what to change and what to re-run would be good.

**Comment by LuciMoore** [comment]
repo is no longer being maintained!
